version: '3.5'
networks:
  default:
    name: tks-platform
# enforce some dependencies
services:
  #  ================================== Zookeeper ========================================== #
  oracle-xe:
    image: chameleon82/oracle-xe-10g
    container_name: oracle-xe
    hostname: oracle-xe
    ports:
      - 1521:1521
    restart: unless-stopped
