nexus.httpclient.proxy.http.enabled=true
nexus.httpclient.proxy.http.host=your-proxy-host
nexus.httpclient.proxy.http.port=3128
nexus.httpclient.proxy.https.enabled=true
nexus.httpclient.proxy.https.host=your-proxy-host
nexus.httpclient.proxy.https.port=3128
nexus.httpclient.proxy.http.nonProxyHosts=localhost|127.0.0.1|10.89.*